#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTS_PRG2_20212_59
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="UTS")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertms_karyawan(ms_karyawan instance);
    partial void Updatems_karyawan(ms_karyawan instance);
    partial void Deletems_karyawan(ms_karyawan instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::UTS_PRG2_20212_59.Properties.Settings.Default.UTSConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ms_karyawan> ms_karyawans
		{
			get
			{
				return this.GetTable<ms_karyawan>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ms_karyawan")]
	public partial class ms_karyawan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id_karyawan;
		
		private string _nama_karyawan;
		
		private string _jenis_kelamin;
		
		private string _email;
		
		private string _no_telepon;
		
		private string _alamat;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_karyawanChanging(string value);
    partial void Onid_karyawanChanged();
    partial void Onnama_karyawanChanging(string value);
    partial void Onnama_karyawanChanged();
    partial void Onjenis_kelaminChanging(string value);
    partial void Onjenis_kelaminChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onno_teleponChanging(string value);
    partial void Onno_teleponChanged();
    partial void OnalamatChanging(string value);
    partial void OnalamatChanged();
    #endregion
		
		public ms_karyawan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_karyawan", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id_karyawan
		{
			get
			{
				return this._id_karyawan;
			}
			set
			{
				if ((this._id_karyawan != value))
				{
					this.Onid_karyawanChanging(value);
					this.SendPropertyChanging();
					this._id_karyawan = value;
					this.SendPropertyChanged("id_karyawan");
					this.Onid_karyawanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nama_karyawan", DbType="VarChar(50)")]
		public string nama_karyawan
		{
			get
			{
				return this._nama_karyawan;
			}
			set
			{
				if ((this._nama_karyawan != value))
				{
					this.Onnama_karyawanChanging(value);
					this.SendPropertyChanging();
					this._nama_karyawan = value;
					this.SendPropertyChanged("nama_karyawan");
					this.Onnama_karyawanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_jenis_kelamin", DbType="VarChar(10)")]
		public string jenis_kelamin
		{
			get
			{
				return this._jenis_kelamin;
			}
			set
			{
				if ((this._jenis_kelamin != value))
				{
					this.Onjenis_kelaminChanging(value);
					this.SendPropertyChanging();
					this._jenis_kelamin = value;
					this.SendPropertyChanged("jenis_kelamin");
					this.Onjenis_kelaminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(20)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no_telepon", DbType="VarChar(13)")]
		public string no_telepon
		{
			get
			{
				return this._no_telepon;
			}
			set
			{
				if ((this._no_telepon != value))
				{
					this.Onno_teleponChanging(value);
					this.SendPropertyChanging();
					this._no_telepon = value;
					this.SendPropertyChanged("no_telepon");
					this.Onno_teleponChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alamat", DbType="VarChar(50)")]
		public string alamat
		{
			get
			{
				return this._alamat;
			}
			set
			{
				if ((this._alamat != value))
				{
					this.OnalamatChanging(value);
					this.SendPropertyChanging();
					this._alamat = value;
					this.SendPropertyChanged("alamat");
					this.OnalamatChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
